name: merge

on:
  pull_request:
    types: [opened, closed, edited]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Configure Git
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

    - name: Echo something
      run: |
        echo $GITHUB_REF
        echo $GITHUB_WORKSPACE
        echo $GITHUB_EVENT_NAME